spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/tenpo
    username: tenpo
    password: tenpo123
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

external:
  service:
    percentage:
      url: http://localhost:8081
      timeout: 5s

logging:
  level:
    com.jesuspacheco.tenpo: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG